version: "3.7"
services:
  app:
    build: .
    container_name: laravel-app
    environment:
      - LANG=en_US.utf8
      - TZ=America/Maceio
    working_dir: /var/www/
    ports:
      - 8000:8000
    command: "php artisan serve --host=0.0.0.0 --port=8000"
    volumes:
      - ./:/var/www

  mariadb:
    container_name: mariadb
    image: mariadb:10.6.22
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql-mode=''
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    ports:
      - 3306:3306
    volumes:
      - ./mariadb_data:/var/lib/mysql:Z

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5.2.3
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root
      - TZ=America/Sao_Paulo
      - UPLOAD_LIMIT=900M
    ports:
      - "3101:80"
